services:
  portfolio-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./knowledge.txt:/app/knowledge.txt
    restart: unless-stopped
